
server:
  port: 8081

spring:
  application:
    name: 'fornecedor'
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/fornecedor #Antes crie o banco de dados "fornecedor"
  jpa:
    hibernate:
      ddl-auto: update #Use "create" na primeira vez depois "update"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka