
server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /home/pedro/devsystem/project/java/alura/microservices/microservices-spring-cloud/microservice-repo